---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: configure
  run_list: ['recipe[kafka::configure]']
  attributes: {}
- name: binary
  run_list: ['recipe[kafka::binary]']
  attributes: {}
- name: source
  run_list: ['recipe[kafka::source]']
  attributes: {}
- name: standalone
  run_list: ['recipe[kafka::standalone]']
  attributes: {}
