---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
  - name: centos-5.9
  - name: fedora-18
  - name: fedora-19

suites:
  - name: configure
    run_list:
      - recipe[kafka::configure]
    attributes:
      java:
        jdk_version: 7
  - name: binary
    run_list:
      - recipe[kafka::binary]
    attributes:
      java:
        jdk_version: 7
  - name: source
    run_list:
      - recipe[kafka::source]
    attributes:
      java:
        jdk_version: 7
  - name: standalone
    run_list:
      - recipe[kafka::standalone]
    attributes:
      java:
        jdk_version: 7
