---
driver:
  name: 'docker'
  memory: '1024m'
  cpu: 4
provisioner:
  name: 'chef_solo'
  require_chef_omnibus: false
  attributes:
    kafka:
      log4j:
        appenders:
          zookeeperAppender:
            type: 'org.apache.log4j.FileAppender'
            file: '/var/log/kafka/zookeeper.log'
            layout:
              type: 'org.apache.log4j.PatternLayout'
              conversion_pattern: '[%d] %p %m (%c)%n'
        loggers:
          org.apache.zookeeper:
            level: 'INFO'
            appender: 'zookeeperAppender'
            additivity: false
platforms:
  - name: centos-6.4
    driver_config:
      provision_command:
        - yum install -y tar java-1.7.0-openjdk java-1.7.0-openjdk-devel
        - curl -L https://www.getchef.com/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '11.16.4') %>
  - name: debian-7.4
    driver_config:
      provision_command:
        - apt-get install -y openjdk-7-jre-headless
        - apt-get install -y net-tools
        - curl -L https://www.getchef.com/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '11.16.4') %>
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - apt-get install -y openjdk-7-jre-headless
        - curl -L https://www.getchef.com/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '11.16.4') %>
suites:
  - name: init-style-sysv
    run_list:
      - recipe[kafka::default]
    attributes:
      kafka:
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        scala_version: <%= ENV.fetch('SCALA_VERSION', '2.9.2') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        ulimit_file: 128000
        broker:
          controlled_shutdown_enable: <%= ENV.fetch('KAFKA_CTRL_SHUTDOWN', nil) %>
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
