---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: configuration
    run_list:
      - recipe[kafka::setup]
      - recipe[kafka::configure]
    attributes:
      java:
        jdk_version: 7
  - name: binary
    run_list:
      - recipe[java]
      - recipe[kafka::binary]
    attributes:
      java:
        jdk_version: 7
  - name: source
    run_list:
      - recipe[java]
      - recipe[kafka::source]
    attributes:
      java:
        jdk_version: 7
  - name: zookeeper
    run_list:
      - recipe[java]
      - recipe[kafka::zookeeper]
    attributes:
      java:
        jdk_version: 7
