language: ruby
script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/chef-11.4.4.gemfile
  - gemfiles/chef-11.6.0.gemfile
  - gemfiles/chef-11.8.0.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/chef-11.4.4.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/chef-11.4.4.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/chef-11.4.4.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/chef-11.6.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/chef-11.8.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/chef-11.4.4.gemfile
